# Notebook B — Race Metadata Loader
Load the race discovery CSV from Notebook A, filter it, and prepare a clean table for metadata loading.

In [1]:
import pandas as pd
from pathlib import Path

## Configuration

In [2]:
# Path to the race_discovery CSV from Notebook A
# Leave as None to auto-detect the most recent file, or set explicitly:
#   DISCOVERY_CSV = Path('outputs/race_discovery/race_discovery_20260509.csv')
DISCOVERY_CSV = Path('outputs/race_discovery/race_discovery_20260509.csv')

## Load Discovery CSV

In [4]:
discovery_dir = Path('outputs/notebook_a_race_discovery')

if DISCOVERY_CSV:
    csv_path = Path(DISCOVERY_CSV)
else:
    candidates = sorted(discovery_dir.glob('race_discovery_*.csv'), reverse=True)
    if not candidates:
        raise FileNotFoundError(f'No race_discovery_*.csv found in {discovery_dir}')
    csv_path = candidates[0]

print(f'Loaded: {csv_path}')
df = pd.read_csv(csv_path)
print(f'Rows: {len(df)}')
df

Loaded: outputs\race_discovery\race_discovery_20260509.csv
Rows: 11

,race_id,race_name,event_id,event_name,distance,start_time
0,32802,Farm Bureau Watermelon Classic 5k Run/Walk,1155721,2026 Farm Bureau Watermelon Classic 5k RUN,5K,7/4/2026 07:30
1,32802,Farm Bureau Watermelon Classic 5k Run/Walk,987494,2025 Farm Bureau Watermelon Classic 5k RUN,5K,7/4/2025 07:30
2,32802,Farm Bureau Watermelon Classic 5k Run/Walk,843361,2024 Farm Bureau Watermelon Classic 5k RUN,5K,7/4/2024 07:30
3,32802,Farm Bureau Watermelon Classic 5k Run/Walk,698223,2023 Farm Bureau Watermelon Classic 5k RUN,5K,7/4/2023 07:30
4,32802,Farm Bureau Watermelon Classic 5k Run/Walk,609109,2022 Farm Bureau Watermelon Classic 5k RUN,5K,7/4/2022 07:30
5,32802,Farm Bureau Watermelon Classic 5k Run/Walk,495705,2021 Farm Bureau Watermelon Classic 5k RUN,5K,7/3/2021 07:30
6,32802,Farm Bureau Watermelon Classic 5k Run/Walk,407416,2020 Farm Bureau Watermelon Classic 5k Run,5K,7/4/2020 00:00
7,32802,Farm Bureau Watermelon Classic 5k Run/Walk,308814,2019 Farm Bureau Watermelon Classic 5k Run,5K,7/4/2019 07:30
8,32802,Farm Bureau Watermelon Classic 5k Run/Walk,233263,2018 Farm Bureau Watermelon Classic 5k Run,5K,7/4/2018 07:30
9,32802,Farm Bureau Watermelon Classic 5k Run/Walk,147717,2017 Farm Bureau Watermelon Classic 5k Run,5K,7/4/2017 07:30
10,32802,Farm Bureau Watermelon Classic 5k Run/Walk,103043,2016 Farm Bureau Watermelon Classic 5k Run,5K,7/4/2016 07:30

## Filter

In [5]:
df_filtered = df.copy()

# Add filters here, e.g.:
# df_filtered = df_filtered[df_filtered['distance'] == '5K']

print(f'Rows after filtering: {len(df_filtered)}')
df_filtered

Rows after filtering: 11

,race_id,race_name,event_id,event_name,distance,start_time
0,32802,Farm Bureau Watermelon Classic 5k Run/Walk,1155721,2026 Farm Bureau Watermelon Classic 5k RUN,5K,7/4/2026 07:30
1,32802,Farm Bureau Watermelon Classic 5k Run/Walk,987494,2025 Farm Bureau Watermelon Classic 5k RUN,5K,7/4/2025 07:30
2,32802,Farm Bureau Watermelon Classic 5k Run/Walk,843361,2024 Farm Bureau Watermelon Classic 5k RUN,5K,7/4/2024 07:30
3,32802,Farm Bureau Watermelon Classic 5k Run/Walk,698223,2023 Farm Bureau Watermelon Classic 5k RUN,5K,7/4/2023 07:30
4,32802,Farm Bureau Watermelon Classic 5k Run/Walk,609109,2022 Farm Bureau Watermelon Classic 5k RUN,5K,7/4/2022 07:30
5,32802,Farm Bureau Watermelon Classic 5k Run/Walk,495705,2021 Farm Bureau Watermelon Classic 5k RUN,5K,7/3/2021 07:30
6,32802,Farm Bureau Watermelon Classic 5k Run/Walk,407416,2020 Farm Bureau Watermelon Classic 5k Run,5K,7/4/2020 00:00
7,32802,Farm Bureau Watermelon Classic 5k Run/Walk,308814,2019 Farm Bureau Watermelon Classic 5k Run,5K,7/4/2019 07:30
8,32802,Farm Bureau Watermelon Classic 5k Run/Walk,233263,2018 Farm Bureau Watermelon Classic 5k Run,5K,7/4/2018 07:30
9,32802,Farm Bureau Watermelon Classic 5k Run/Walk,147717,2017 Farm Bureau Watermelon Classic 5k Run,5K,7/4/2017 07:30
10,32802,Farm Bureau Watermelon Classic 5k Run/Walk,103043,2016 Farm Bureau Watermelon Classic 5k Run,5K,7/4/2016 07:30

## Prepare for Metadata Load

In [ ]:
keep_cols = [c for c in ['race_id', 'race_name', 'event_id', 'event_name', 'distance',
                          'start_date', 'city', 'state', 'zipcode', 'race_url']
             if c in df_filtered.columns]

df_metadata = df_filtered[keep_cols].copy()
df_metadata['race_id'] = pd.to_numeric(df_metadata['race_id'], errors='coerce').astype('Int64')

if 'event_id' in df_metadata.columns:
    df_metadata['event_id'] = pd.to_numeric(df_metadata['event_id'], errors='coerce').astype('Int64')

print(f'Ready to load: {len(df_metadata)} rows, {len(df_metadata["race_id"].unique())} races')
df_metadata

## Load Metadata

In [ ]:
# TODO: load df_metadata into the metadata store
pass